version: '3.8'

services:
  web:
    container_name: bizcheck-web
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GIT_REPO_URL: https://github.com/field-animal/biznum-check.git
        GIT_BRANCH: main
    ports:
      - "8110:80"
    restart: always
